server:
  port: 2137
  servlet:
    context-path: /api


spring:
  jpa:
    hibernate:
      ddl-auto: create-drop #change to update when models not modify (with update old columns will not be dropped)
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/usos
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver

usos:
  app:
    jwtSecret: meowmeowlittlesecret
    expirationTime: 3600000




