server:
  port: 2137
  servlet:
    context-path: /api



spring:
  jpa:
    hibernate:
      ddl-auto: create-drop #change to update when models not modify (with update old columns will not be dropped)
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/usos?useUnicode=yes&characterEncoding=UTF-8
    password:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: usos.fibi@gmail.com
    password: Fibi123@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true



usos:
  app:
    jwtSecret: meowmeowlittlesecret
    expirationTime: 3600000
    payu:
      tokenRequestUrl: https://secure.snd.payu.com/pl/standard/user/oauth/authorize
      orderRequestUrl: https://secure.snd.payu.com/api/v2_1/orders/
      clientId: 389108
      secret: d7d564dd92ee2293b374a8d108ca7768
      notifyUrl: http://145.239.89.7:2137/api/payment/notify
      merchantPosId: 389108
      continueUrl: https://localhost:8081/student/payments




